upstream php_backends {
    server php-fpm-1:9000;
    server php-fpm-2:9000;
    server php-fpm-3:9000;
    server php-fpm-4:9000;
}

server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        fastcgi_pass php_backends;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
