upstream php_backends {
    least_conn;
    server php-fpm-1:9000;
    server php-fpm-2:9000;
    server php-fpm-3:9000;
    server php-fpm-4:9000;
}

server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html index.htm;

    # Отдача статики напрямую через Nginx
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
        root /var/www/html/public;
        log_not_found off;
        access_log off;
        expires max;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass php_backends;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
